-- Sample Products for FJ Jewelry Store
-- Run this in your Supabase SQL Editor to add sample products

-- First, get the category IDs
WITH category_ids AS (
  SELECT 
    (SELECT id FROM product_categories WHERE slug = 'necklaces') as necklaces_id,
    (SELECT id FROM product_categories WHERE slug = 'earrings') as earrings_id,
    (SELECT id FROM product_categories WHERE slug = 'bracelets') as bracelets_id,
    (SELECT id FROM product_categories WHERE slug = 'rings') as rings_id
)

-- Insert sample products
INSERT INTO public.products (
  name, 
  slug, 
  description, 
  short_description, 
  sku, 
  price, 
  compare_price, 
  category_id, 
  brand, 
  stock_quantity, 
  is_active, 
  is_featured,
  tags,
  materials,
  care_instructions,
  weight,
  dimensions
) VALUES
-- Necklaces
(
  'Wildflower Dreams Necklace', 
  'wildflower-dreams-necklace',
  'A delicate handcrafted necklace inspired by wildflowers dancing in the summer breeze. Each piece features intricate floral details and sparkles with natural beauty. The pendant showcases a beautifully crafted wildflower motif with tiny cubic zirconia stones that catch the light like morning dew. This piece represents the free spirit and celebrates the beauty found in nature''s spontaneous moments.',
  'Handcrafted floral necklace with delicate wildflower design',
  'WDN-001',
  89.99,
  119.99,
  (SELECT necklaces_id FROM category_ids),
  'FJ Collection',
  15,
  true,
  true,
  '["wildflower", "nature", "delicate", "handcrafted"]'::jsonb,
  '["sterling silver", "gold plating", "cubic zirconia"]'::jsonb,
  'Clean gently with a soft cloth. Avoid contact with water, perfumes, and lotions. Store in a dry place.',
  3.2,
  '{"length": "18 inches", "pendant_width": "12mm", "pendant_height": "15mm"}'::jsonb
),
(
  'Celestial Moon Necklace',
  'celestial-moon-necklace', 
  'Embrace the magic of the night sky with this enchanting moon-phase necklace. Perfect for dreamers and stargazers. The design features a crescent moon that seems to glow with an inner light, connected to delicate star charms that dance along the chain. Each phase of the moon is represented in miniature detail, creating a piece that tells the story of celestial cycles.',
  'Mystical moon-phase necklace with celestial charm',
  'CMN-002',
  74.99,
  null,
  (SELECT necklaces_id FROM category_ids),
  'FJ Collection',
  12,
  true,
  true,
  '["celestial", "moon", "mystical", "night sky"]'::jsonb,
  '["rose gold", "sterling silver"]'::jsonb,
  'Wipe with a dry cloth after wear. Store separately to avoid scratching.',
  2.8,
  '{"length": "16 inches", "moon_pendant": "10mm", "adjustable": "yes"}'::jsonb
),
(
  'Garden of Dreams Pendant',
  'garden-of-dreams-pendant',
  'A romantic pendant featuring a miniature garden scene, complete with tiny flowers and leaves that catch the light beautifully. This intricate piece showcases the artisan''s attention to detail with hand-painted enamel work that brings the garden to life. Each flower petal is carefully crafted to create depth and movement, making this pendant a wearable work of art.',
  'Romantic garden-themed pendant necklace',
  'GDP-003',
  65.99,
  85.99,
  (SELECT necklaces_id FROM category_ids),
  'FJ Collection',
  8,
  true,
  false,
  '["garden", "romantic", "flowers", "pendant"]'::jsonb,
  '["14k gold filled", "enamel details"]'::jsonb,
  'Handle with care due to enamel details. Clean with warm soapy water and soft brush.',
  4.1,
  '{"length": "20 inches", "pendant_diameter": "18mm", "thickness": "3mm"}'::jsonb
),

-- Earrings
(
  'Butterfly Whispers Earrings',
  'butterfly-whispers-earrings',
  'Delicate butterfly earrings that seem to flutter with every movement. These ethereal pieces add a touch of whimsy to any outfit. Crafted with ultra-light materials, they feature intricate wing details and tiny pearl accents that catch the light. The butterflies appear to be in mid-flight, creating a sense of movement and grace.',
  'Delicate butterfly drop earrings with ethereal design',
  'BWE-004',
  45.99,
  59.99,
  (SELECT earrings_id FROM category_ids),
  'FJ Collection',
  20,
  true,
  true,
  '["butterfly", "whimsical", "delicate", "drop earrings"]'::jsonb,
  '["sterling silver", "pearl accents"]'::jsonb,
  'Store in individual pouches to prevent tangling. Clean with jewelry polishing cloth.',
  1.5,
  '{"total_length": "35mm", "butterfly_width": "12mm", "drop_style": "yes"}'::jsonb
),
(
  'Stardust Hoops',
  'stardust-hoops',
  'Sparkly hoop earrings dusted with tiny crystals that catch the light like stardust. Perfect for both day and night wear. The hoops feature a unique textured surface that creates countless points of light reflection, making them sparkle from every angle. The comfortable closure ensures they stay secure during any activity.',
  'Sparkly crystal-dusted hoop earrings',
  'SDH-005',
  52.99,
  null,
  (SELECT earrings_id FROM category_ids),
  'FJ Collection',
  18,
  true,
  false,
  '["hoops", "sparkly", "crystals", "versatile"]'::jsonb,
  '["gold plated", "crystal details"]'::jsonb,
  'Clean regularly with soft cloth to maintain sparkle. Avoid harsh chemicals.',
  2.3,
  '{"diameter": "25mm", "thickness": "3mm", "closure": "hinged"}'::jsonb
),
(
  'Enchanted Forest Studs',
  'enchanted-forest-studs',
  'Tiny leaf-shaped studs that bring the magic of an enchanted forest to your ears. Perfect for everyday wear. Each leaf features intricate vein details and a subtle green stone that evokes the fresh feeling of walking through a magical woodland. The organic shapes make each pair slightly unique.',
  'Leaf-shaped stud earrings with forest magic',
  'EFS-006',
  32.99,
  42.99,
  (SELECT earrings_id FROM category_ids),
  'FJ Collection',
  25,
  true,
  false,
  '["studs", "leaves", "forest", "everyday"]'::jsonb,
  '["recycled gold", "natural stones"]'::jsonb,
  'Gentle daily wear piece. Clean with warm water and mild soap.',
  0.8,
  '{"leaf_length": "8mm", "leaf_width": "6mm", "post_type": "surgical steel"}'::jsonb
),

-- Bracelets
(
  'Harmony Chain Bracelet',
  'harmony-chain-bracelet',
  'A delicate chain bracelet with small charms that represent harmony and balance. Each charm tells a story of peace and tranquility. The bracelet features symbols from different cultures that represent unity, including a lotus flower, infinity symbol, and peaceful dove. The adjustable length ensures a perfect fit for any wrist.',
  'Delicate charm bracelet symbolizing harmony',
  'HCB-007',
  58.99,
  78.99,
  (SELECT bracelets_id FROM category_ids),
  'FJ Collection',
  14,
  true,
  true,
  '["chain", "charms", "harmony", "balance"]'::jsonb,
  '["sterling silver", "charm details"]'::jsonb,
  'Avoid water exposure. Clean charms individually with soft brush and mild soap.',
  5.2,
  '{"length": "7-8 inches", "chain_width": "2mm", "adjustable": "yes"}'::jsonb
),
(
  'Ocean Waves Bangle',
  'ocean-waves-bangle',
  'A flowing bangle inspired by ocean waves, with a textured surface that mimics the movement of water. The undulating surface creates an ever-changing play of light and shadow, reminiscent of sunlight dancing on ocean waves. This substantial piece makes a statement while remaining comfortable for all-day wear.',
  'Textured bangle inspired by ocean waves',
  'OWB-008',
  42.99,
  null,
  (SELECT bracelets_id FROM category_ids),
  'FJ Collection',
  10,
  true,
  false,
  '["bangle", "ocean", "waves", "textured"]'::jsonb,
  '["recycled silver", "ocean-inspired"]'::jsonb,
  'Polish regularly to maintain luster. Safe for occasional water exposure.',
  12.5,
  '{"inner_diameter": "65mm", "width": "8mm", "thickness": "4mm"}'::jsonb
),

-- Rings
(
  'Bloom Ring',
  'bloom-ring',
  'A beautiful ring featuring a blooming flower design with petals that wrap around your finger like nature''s embrace. The three-dimensional flower seems to grow from the band, with each petal carefully shaped to create realistic depth and movement. Tiny pink stones add color and sparkle to the center of the bloom.',
  'Floral ring with blooming flower design',
  'BR-009',
  67.99,
  89.99,
  (SELECT rings_id FROM category_ids),
  'FJ Collection',
  12,
  true,
  true,
  '["ring", "flower", "bloom", "nature"]'::jsonb,
  '["rose gold", "pink stones"]'::jsonb,
  'Remove before washing hands. Clean with jewelry cleaner and soft cloth.',
  3.8,
  '{"sizes_available": "5-10", "band_width": "3mm", "flower_diameter": "12mm"}'::jsonb
),
(
  'Infinity Dreams Ring',
  'infinity-dreams-ring',
  'A stunning infinity symbol ring that represents endless possibilities and eternal love. The seamless infinity symbol is crafted to appear as if it floats above the finger, creating an elegant and meaningful piece. Tiny diamonds trace the infinity curves, adding sparkle to this symbolic design.',
  'Infinity symbol ring representing endless love',
  'IDR-010',
  55.99,
  null,
  (SELECT rings_id FROM category_ids),
  'FJ Collection',
  16,
  true,
  false,
  '["infinity", "symbol", "love", "dreams"]'::jsonb,
  '["white gold", "diamond accents"]'::jsonb,
  'Professional cleaning recommended every 6 months. Avoid harsh chemicals.',
  2.9,
  '{"sizes_available": "4-9", "band_width": "2mm", "infinity_width": "8mm"}'::jsonb
),
(
  'Mystical Star Ring',
  'mystical-star-ring',
  'Channel the power of the stars with this mystical ring featuring a celestial star design. The star seems to radiate energy with its pointed rays extending outward from a central stone. This statement piece is perfect for those who feel connected to cosmic energy and celestial guidance.',
  'Celestial star ring with mystical energy',
  'MSR-011',
  49.99,
  64.99,
  (SELECT rings_id FROM category_ids),
  'FJ Collection',
  9,
  true,
  false,
  '["star", "celestial", "mystical", "power"]'::jsonb,
  '["sterling silver", "star details"]'::jsonb,
  'Store away from other jewelry to prevent scratching of star points.',
  4.2,
  '{"sizes_available": "5-9", "star_diameter": "15mm", "band_width": "4mm"}'::jsonb
);

-- Success message
SELECT 'Sample products with detailed information added successfully! 🌟' as message; 