export interface MoodData {
  id: string
  emoji: string
  name: string
  quote: string
  message: string
  product: string
  colors: string[]
  songs: { title: string; artist: string }[] // Changed to array of songs
}

export const moods: MoodData[] = [
  {
    id: "blossoming-babe",
    emoji: "🌷",
    name: "Blossoming Babe",
    quote: "You're not behind — you're just still blooming.",
    message: "Girl, your petals are unfolding. Sip your tea, adjust your crown, and bloom on your own timeline. 🌸",
    product: "Whisper Bloom Earrings",
    colors: ["#FFE4E6", "#FFF7ED", "#F8BBD9"],
    songs: [
      { title: "Bloom", artist: "Troye Sivan" },
      { title: "Sunflower", artist: "Post Malone" },
      { title: "Flowers", artist: "Miley Cyrus" },
      { title: "Petal", artist: "Johnny Stimson" },
    ],
  },
  {
    id: "main-character",
    emoji: "🔥",
    name: "Main Character Energy",
    quote: "If you're too much, go find less.",
    message: "You are the plot twist. Strut like the sidewalk owes you rent, sparkle trailing behind. 💅",
    product: "Wisteria Blaze Ring",
    colors: ["#FFD700", "#E6E6FA", "#FF6B6B"],
    songs: [
      { title: "Confident", artist: "Demi Lovato" },
      { title: "Boss Bitch", artist: "Doja Cat" },
      { title: "Good as Hell", artist: "Lizzo" },
      { title: "That Bitch", artist: "Bea Miller" },
    ],
  },
  {
    id: "softly-dramatic",
    emoji: "🌧",
    name: "Softly Dramatic",
    quote: "Cried at 10, thrived by 12.",
    message: "You've got mascara tears and a matching manicure. Chaos? Beautifully curated. 🎭",
    product: "Rainkiss Drops Pendant",
    colors: ["#4682B4", "#F8F8FF", "#B19CD9"],
    songs: [
      { title: "Liability", artist: "Lorde" },
      { title: "Breathe Me", artist: "Sia" },
      { title: "Heavy", artist: "Linkin Park ft. Kiiara" },
      { title: "Hurt", artist: "Johnny Cash" },
    ],
  },
  {
    id: "delicate-deadly",
    emoji: "🧁",
    name: "Delicate but Deadly",
    quote: "I'm soft but I sting. I'm frosting with a blade.",
    message: "You're sugar and smoke. People mistake cute for calm — bless their hearts. 🍰",
    product: "Cherry Pop Anklet",
    colors: ["#FFB6C1", "#DC143C", "#FFF0F5"],
    songs: [
      { title: "Sweet but Psycho", artist: "Ava Max" },
      { title: "Dollhouse", artist: "Melanie Martinez" },
      { title: "Therefore I Am", artist: "Billie Eilish" },
      { title: "Bad Guy", artist: "Billie Eilish" },
    ],
  },
  {
    id: "ethereal-chaos",
    emoji: "🌙",
    name: "Ethereal Chaos",
    quote: "Floating through life... stylishly overwhelmed.",
    message: "You're 90% emotion, 10% glitter. Confused? Yes. Stunning? Absolutely. ✨",
    product: "Moonmilk Chain",
    colors: ["#C0C0C0", "#F0F8FF", "#E6E6FA"],
    songs: [
      { title: "Strawberry Moon", artist: "IU" },
      { title: "Space Song", artist: "Beach House" },
      { title: "Dreams Tonite", artist: "Alvvays" },
      { title: "Myth", artist: "Beach House" },
    ],
  },
  {
    id: "sensual-sentimental",
    emoji: "🍓",
    name: "Sensual & Sentimental",
    quote: "Romanticizing my life like it's my job.",
    message: "You feel everything, love deeply, and cry over a cute cloud. And we adore that for you. 💌",
    product: "Loveberry Locket",
    colors: ["#FF69B4", "#DC143C", "#FFB6C1"],
    songs: [
      { title: "Invisible String", artist: "Taylor Swift" },
      { title: "Adorn", artist: "Miguel" },
      { title: "Golden", artist: "Harry Styles" },
      { title: "Best Part", artist: "Daniel Caesar ft. H.E.R." },
    ],
  },
  {
    id: "just-vibing",
    emoji: "🦋",
    name: "IDK I'm Just Vibing",
    quote: "Mood: ambiguous but accessorized.",
    message: "Are you thriving? Are you spiraling? Who knows. But you look hot. Keep vibing. ✨",
    product: "Butterfly Dreams Bracelet",
    colors: ["#DDA0DD", "#98FB98", "#FFE4B5"],
    songs: [
      { title: "Good 4 U", artist: "Olivia Rodrigo" },
      { title: "Levitating", artist: "Dua Lipa" },
      { title: "Blinding Lights", artist: "The Weeknd" },
      { title: "As It Was", artist: "Harry Styles" },
    ],
  },
  {
    id: "emotionally-unavailable",
    emoji: "💅",
    name: "Emotionally Unavailable but Aesthetic",
    quote: "Don't text. I'm curating a moodboard.",
    message: "Healing? Maybe. Avoiding? Also maybe. Either way, your outfit is doing the work. 💫",
    product: "Detached Darling Ring",
    colors: ["#E6E6FA", "#D3D3D3", "#F5F5F5"],
    songs: [
      { title: "Therefore I Am", artist: "Billie Eilish" },
      { title: "My Boy", artist: "Billie Eilish" },
      { title: "Happier Than Ever", artist: "Billie Eilish" },
      { title: "I Don't Care", artist: "Ed Sheeran & Justin Bieber" },
    ],
  },
  {
    id: "tired-trying",
    emoji: "💌",
    name: "Tired but Trying",
    quote: "Running on dreams and iced coffee.",
    message: "You're exhausted but radiant. Still showing up in lilac and gloss? That's power. ☕",
    product: "Caffeine Queen Necklace",
    colors: ["#E6E6FA", "#F5F5DC", "#DDA0DD"],
    songs: [
      { title: "Tired", artist: "beabadoobee" },
      { title: "Coffee", artist: "beabadoobee" },
      { title: "Breathe", artist: "Taylor Swift" },
      { title: "Exhale", artist: "Sabrina Carpenter" },
    ],
  },
  {
    id: "baby-boundaries",
    emoji: "💖",
    name: "I'm Baby, but With Boundaries",
    quote: "I'm delicate, not dumb.",
    message: "You're soft-spoken but iron-willed. Baby voice, executive decisions. 👑",
    product: "Sweet Steel Studs",
    colors: ["#FFB6C1", "#FF1493", "#FFC0CB"],
    songs: [
      { title: "Pretty Hurts", artist: "Beyoncé" },
      { title: "Respect", artist: "Aretha Franklin" },
      { title: "Stronger", artist: "Kelly Clarkson" },
      { title: "Fight Song", artist: "Rachel Platten" },
    ],
  },
  {
    id: "socially-depleted",
    emoji: "😴",
    name: "Socially Depleted Fairy",
    quote: "I love you, but I need to lie down now.",
    message: "You've given the world enough sparkle today. Go hide in your blanket fort, princess. 🧚‍♀️",
    product: "Introvert's Crown",
    colors: ["#E6E6FA", "#F0F8FF", "#F8F8FF"],
    songs: [
      { title: "Breathe Me", artist: "Sia" },
      { title: "Quiet", artist: "MILCK" },
      { title: "Alone", artist: "Marshmello" },
      { title: "Solitude", artist: "Billie Holiday" },
    ],
  },
  {
    id: "overthinking",
    emoji: "✨",
    name: "Chronically Overthinking",
    quote: "Sorry, I overanalyzed your text... for the 12th time.",
    message: "Girl, your brain's doing cardio, but your jewelry is giving calm. Balance. 🧠",
    product: "Mindful Moments Bracelet",
    colors: ["#DDA0DD", "#F0E68C", "#E6E6FA"],
    songs: [
      { title: "Anxious", artist: "ginuwine" },
      { title: "Stressed Out", artist: "Twenty One Pilots" },
      { title: "Mind Over Matter", artist: "Young the Giant" },
      { title: "Overthinking", artist: "ROLE MODEL" },
    ],
  },
  {
    id: "hot-mess",
    emoji: "💃",
    name: "Hot Mess but Make It Fashion",
    quote: "I've got 3 emotions and they're all dramatic.",
    message: "You're unhinged, unbothered, and unmatched. We support your chaos. 🔥",
    product: "Chaos Couture Earrings",
    colors: ["#FF69B4", "#FFD700", "#FF6347"],
    songs: [
      { title: "Crazy", artist: "Britney Spears" },
      { title: "Hot Mess", artist: "Cobra Starship" },
      { title: "Complicated", artist: "Avril Lavigne" },
      { title: "Unstable", artist: "Justin Bieber" },
    ],
  },
]
