export interface QuizOption {
  text: string
  archetype: string
  score: number
  emoji: string
}

export interface QuizQuestion {
  question: string
  options: QuizOption[]
}

export const quizQuestions: QuizQuestion[] = [
  {
    question: "When getting dressed, your first thought is...",
    options: [
      {
        text: "Is this outfit telling the right story?",
        score: 1,
        emoji: "🪽",
        archetype: "The Timeless Romantic",
      },
      {
        text: "Does this feel balanced and intentional?",
        score: 2,
        emoji: "🪞",
        archetype: "The Grounded Stylist",
      },
      {
        text: "How does this make my soul feel?",
        score: 3,
        emoji: "🌿",
        archetype: "The Natural Creative",
      },
      {
        text: "Will this work with my planned activities?",
        score: 4,
        emoji: "📐",
        archetype: "The Intentional Dresser",
      },
      {
        text: "What mood am I channeling today?",
        score: 5,
        emoji: "🌙",
        archetype: "The Sentimental Dreamer",
      },
      {
        text: "What if I tried something completely different?",
        score: 6,
        emoji: "🎨",
        archetype: "The Playful Explorer",
      },
      {
        text: "How can I make this look more dramatic?",
        score: 7,
        emoji: "💋",
        archetype: "The Confident Maximalist",
      },
      {
        text: "Whatever feels right in this moment",
        score: 8,
        emoji: "🔥",
        archetype: "The Free Spirit",
      },
      {
        text: "Less is more, but make it powerful",
        score: 9,
        emoji: "🖤",
        archetype: "The Magnetic Minimalist",
      },
      {
        text: "How can I challenge expectations today?",
        score: 10,
        emoji: "🧬",
        archetype: "The Visionary Dresser",
      },
    ],
  },
  {
    question: "You catch your reflection unexpectedly. What's your first thought?",
    options: [
      {
        text: "I feel like myself. Comfortable. I'll probably wear the same go-to pieces.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Polished enough, but I'll fix that one detail before heading out.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Not bad — could use a little color or texture to add personality.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Close, but I think I'll swap something to match the vibe I want.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Something about today feels meaningful. I might wear something with a story.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Let's try something different — why not switch it up?",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold look. Big energy. Let's keep it that way.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Okay, she's a little chaotic, but we're rolling with it.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Clean. Sharp. One statement piece is all I need.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Normal's boring. I'm adding something unexpected today.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "How do you usually handle change — in life, style, or plans?",
    options: [
      {
        text: "I prefer what I know. I take time to adjust, and I usually stick to what works.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "If it makes sense, I adapt. But I like structure and knowing where I'm going.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "I flow with it. I might not love it at first, but I always find a new rhythm.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Change is fine — as long as I can plan for it and keep control over the details.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "I tend to process change emotionally. I need space to reflect before moving forward.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "I don't overthink it. If it feels good, I go with it.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "I own it. Change gives me a chance to show up bigger and better.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Change is just part of the day. I don't plan much, so it doesn't rattle me.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I adjust only if it's worth the energy. I don't follow trends or noise.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I usually create the change. I get bored if things stay the same for too long.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "What's the real reason you wear jewelry — beyond just looking good?",
    options: [
      {
        text: "It reminds me of people I love or moments I want to keep close.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "It completes a look. I feel more put together when I wear it.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "It's how I bring personality into everyday outfits.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "It's a styling tool — I use it to balance, contrast, or elevate.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "It helps me express how I feel, especially when I don't want to say it out loud.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "It's fun. It changes depending on my mood, like clothing for my emotions.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "It's part of my presence. I like standing out and owning the room.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "It's just whatever speaks to me in the moment. No logic, just energy.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "It adds just enough edge or intrigue. One piece can shift the whole vibe.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "It's an art form. I use jewelry to challenge what people expect.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "When you walk into a room and people notice your look, what's your reaction?",
    options: [
      {
        text: "A quiet compliment is sweet, but I don't dress to stand out.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "I appreciate it — it means I got the details right.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "It makes me happy if people notice the little touches.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "It's the goal — I put thought into everything I wear.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "I like when someone senses the mood I'm channeling.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "It depends on the day. Some days I want to blend in, other days I don't.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      { text: "Love it. I dress for the entrance.", archetype: "The Confident Maximalist", score: 7, emoji: "💋" },
      {
        text: "Honestly, I never really notice — I'm just doing me.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I want to be noticed without saying a word. Impact over volume.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "If they're surprised or intrigued, I've done my job.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "What's your relationship with trends?",
    options: [
      {
        text: "I prefer timeless pieces that never go out of style.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "I pick and choose what works for my lifestyle and aesthetic.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "I'm inspired by trends but make them my own.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "I research trends and incorporate them strategically.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "I follow trends that match my current emotional state.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "I love trying new trends — it's like playing dress up!",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "I set trends. Others follow what I'm wearing.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Trends are just suggestions. I do what feels right.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I ignore most trends. My style is intentionally timeless.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I create my own trends by mixing unexpected elements.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "How do you choose what to wear when you're feeling emotional?",
    options: [
      {
        text: "I reach for pieces that comfort me and remind me of happy memories.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "I stick to my tried-and-true outfits that make me feel put together.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "I choose colors and textures that match or soothe my mood.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "I plan outfits that will help me feel confident for the day ahead.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "My jewelry becomes an extension of my feelings — each piece tells a story.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "I experiment with bold choices to shift my energy.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "I dress up even more — looking good helps me feel powerful.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "I wear whatever feels authentic to my current state.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I choose one meaningful piece that grounds me.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I use fashion as art therapy — creating looks that express complex emotions.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "What's your ideal shopping experience?",
    options: [
      {
        text: "Browsing vintage shops and finding pieces with history.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Visiting curated stores with quality pieces that will last.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Discovering local artisans and handmade treasures.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Researching online first, then making strategic purchases.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Finding pieces that speak to my soul, regardless of price or practicality.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Exploring different stores and trying on everything that catches my eye.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Shopping at high-end boutiques where I can make a statement.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Stumbling upon unexpected finds in random places.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Investing in a few perfect pieces from designers I trust.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Seeking out avant-garde designers and experimental pieces.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your favorite piece of jewelry is...",
    options: [
      {
        text: "A locket with a photo or memento inside.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "A simple, well-crafted piece that goes with everything.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Something handmade with natural elements or stones.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "A versatile piece that can be styled multiple ways.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "A dreamy, ethereal piece that feels magical.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Something colorful and playful that makes me smile.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "A bold statement piece that commands attention.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Something I found on my travels with a great story.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "A sleek, architectural piece with clean lines.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Something unusual that people always ask about.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to layering jewelry is...",
    options: [
      {
        text: "Delicate pieces that complement each other with a vintage feel.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Thoughtfully curated pieces in the same metal for a cohesive look.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Mixing textures and natural elements that feel harmonious together.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Strategic combinations that create visual interest without overwhelming.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Pieces that create a dreamy, ethereal story when worn together.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful combinations of colors and charms that make me happy.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "More is more! Bold pieces layered for maximum impact.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Whatever feels right in the moment, even if it breaks the rules.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal but intentional - one or two pieces with perfect placement.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Unexpected combinations that challenge conventional styling.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your favorite gemstone or material is...",
    options: [
      {
        text: "Pearls, cameos, or rose gold with vintage appeal.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "High-quality metals with subtle details and craftsmanship.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Turquoise, wood, or other natural materials with organic textures.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Versatile metals and stones that can transition from day to night.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Moonstone, opal, or anything with a mystical, iridescent quality.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Colorful enamel, beads, or playful materials that pop.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Diamonds, bold gold, or anything that makes a statement.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Materials with meaning or that remind me of special moments.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Sleek metals with minimal embellishment and perfect form.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Unusual materials or combinations that challenge traditional jewelry.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your dream vacation would be...",
    options: [
      {
        text: "A charming European village with cobblestone streets and history.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "A well-planned trip with the perfect balance of relaxation and exploration.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "A nature retreat where I can connect with the outdoors and create.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "A curated experience with access to local culture, food, and design.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "A dreamy destination that feels like stepping into another world.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "A spontaneous adventure with lots of new experiences and fun.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "A luxury destination where I can indulge and be pampered.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Wherever the wind takes me - no itinerary, just following my intuition.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "A thoughtfully designed space with architectural significance and calm energy.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "An off-the-beaten-path destination that few others have experienced.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to self-care is...",
    options: [
      {
        text: "Creating rituals that connect me to tradition and comfort.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Maintaining balance with consistent routines that keep me grounded.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Connecting with nature and engaging in creative activities.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Researching and implementing evidence-based practices for mind and body.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Creating dreamy moments that transport me and honor my emotions.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Trying new wellness trends and keeping things fresh and fun.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Indulging in luxurious experiences that make me feel special.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Listening to my body and doing what feels right in the moment.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Eliminating excess and focusing on high-impact practices.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Creating my own unique practices that others might find unusual.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your home decor style is...",
    options: [
      {
        text: "Vintage-inspired with heirlooms and romantic touches.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Thoughtfully curated with quality pieces that create harmony.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Eclectic and organic with plants, textures, and handmade items.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Functional and intentional with every item serving a purpose.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy and atmospheric with soft lighting and meaningful objects.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful and colorful with unexpected elements and conversation pieces.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold and luxurious with statement pieces and dramatic touches.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Ever-changing and collected from various travels and experiences.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal and curated with clean lines and thoughtful negative space.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Avant-garde with unexpected combinations and artistic statements.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your ideal weekend activity is...",
    options: [
      {
        text: "Visiting a museum, antique shop, or historical site.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "A well-planned day with a balance of productivity and relaxation.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Getting creative with a project or spending time in nature.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Attending a workshop or learning something new and useful.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Getting lost in a book, film, or daydream that transports me.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Trying a new experience or activity I've never done before.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Hosting friends or attending an event where I can shine.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Waking up with no plans and seeing where the day takes me.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "A focused activity that allows me to be fully present and undistracted.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Exploring an unconventional space or experience most people don't know about.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to gift-giving is...",
    options: [
      {
        text: "Thoughtful presents with sentimental value or nostalgic meaning.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Practical but special items that I know the person will use and appreciate.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Handmade or personalized gifts that show creative thought.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Carefully selected items that perfectly match the recipient's needs and taste.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Meaningful gifts that capture a feeling or create a special moment.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Fun, surprising presents that bring joy and playfulness.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Impressive, generous gifts that make a statement.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Spontaneous gifts given whenever I see something that reminds me of someone.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "One perfect, high-quality item rather than multiple smaller gifts.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Unusual or avant-garde items that the person wouldn't find or choose themselves.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your social media aesthetic is...",
    options: [
      {
        text: "Soft, romantic images with a nostalgic or timeless quality.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Curated and cohesive with attention to detail and quality.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Organic and authentic with natural elements and creative moments.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Thoughtfully composed with intentional color schemes and themes.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy and atmospheric with poetic captions and emotional depth.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Colorful and varied with fun moments and new experiences.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold and eye-catching with standout moments and confidence.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Spontaneous and unfiltered, capturing authentic moments as they happen.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal and selective with high-impact images and intentional negative space.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Boundary-pushing with unexpected compositions and artistic vision.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to color in your wardrobe is...",
    options: [
      {
        text: "Soft, romantic hues like blush, cream, and dusty blues.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "A cohesive palette of neutrals with thoughtful pops of color.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Earth tones and natural hues with organic combinations.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Strategic color theory with combinations that enhance my features.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Colors that match my mood or create a specific emotional atmosphere.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful combinations and bright hues that express joy.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold, saturated colors that make a statement and command attention.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Whatever colors feel right in the moment, regardless of 'rules'.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "A limited, precise palette with high contrast and intentional simplicity.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Unexpected color combinations that challenge conventional pairings.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your favorite type of music is...",
    options: [
      {
        text: "Classical, vintage jazz, or nostalgic songs with emotional depth.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Well-crafted songs with thoughtful lyrics and balanced composition.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Folk, acoustic, or music with organic instruments and natural sounds.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Carefully curated playlists for different activities and moods.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy, atmospheric music that transports me emotionally.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Upbeat, fun tracks that make me want to dance and try new moves.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Powerful anthems and dramatic songs with presence and impact.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "An eclectic mix that changes based on my mood and energy.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimalist compositions with intentional space and precision.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Experimental genres and artists who push boundaries and conventions.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to makeup (or lack thereof) is...",
    options: [
      {
        text: "Classic looks with a touch of romance - think rosy cheeks and soft lips.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Polished and enhancing with quality products applied with precision.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Natural and glowing with earth tones and minimal intervention.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Strategic application to enhance features and create balance.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Ethereal and dreamy with shimmers and soft focus effects.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful with color and changing frequently based on mood.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold and glamorous with statement lips or eyes that command attention.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Intuitive and changing - sometimes bare-faced, sometimes expressive.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal but precise with focus on skin quality and subtle enhancement.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Artistic and boundary-pushing with unexpected colors or techniques.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your favorite fictional character's style would be described as...",
    options: [
      {
        text: "Romantic and timeless with feminine details and nostalgic elements.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Polished and put-together with attention to quality and detail.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Artistic and free-flowing with natural elements and textures.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Thoughtfully composed with strategic choices that serve a purpose.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy and ethereal with an emotional or mystical quality.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful and experimental with fun colors and unexpected combinations.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold and confident with statement pieces and dramatic flair.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Effortlessly cool and authentic without trying too hard.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal and precise with perfect proportions and intentional simplicity.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Avant-garde and futuristic with unexpected elements and artistic vision.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "When getting dressed for an important event, you prioritize...",
    options: [
      {
        text: "Looking timeless and elegant with romantic touches.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Being appropriately dressed with quality pieces that show attention to detail.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Expressing my authentic self through personal touches and creativity.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Dressing strategically for the context while still expressing my style.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Creating a mood or feeling that matches the emotional significance.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Having fun with my look and trying something special for the occasion.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Making an entrance and standing out with confidence and presence.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Feeling comfortable and authentic, regardless of expectations.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Creating a powerful, minimal look with perfect execution.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Pushing boundaries with an unexpected approach that challenges norms.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your friends would describe your personal style as...",
    options: [
      {
        text: "Romantic and nostalgic with a timeless elegance.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Put-together and thoughtful with attention to quality and detail.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Creative and natural with an artistic, organic quality.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Intentional and strategic with every element serving a purpose.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy and emotional with a poetic or ethereal quality.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful and experimental with fun elements and joyful energy.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold and confident with statement pieces and dramatic flair.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Effortlessly cool and authentic without trying too hard.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal and precise with perfect proportions and intentional simplicity.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Avant-garde and boundary-pushing with unexpected elements.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "When you receive a compliment on your style, you feel most validated when someone says...",
    options: [
      {
        text: "You look like you stepped out of a classic film or storybook.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "You always look so put-together and thoughtful with your choices.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Your style is so uniquely you - I love how you express yourself.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "I admire how intentional you are with every element of your look.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "There's something magical about how you dress - it creates a mood.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Your style is so fun and playful - it makes me smile!",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "You command the room with your style - it's so bold and confident.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "You have such effortless style - you make it look so natural.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Your minimal style is so powerful - every piece has impact.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I've never seen anyone dress quite like you - it's so innovative.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to organizing your closet is...",
    options: [
      {
        text: "Grouping by sentiment and occasion with special pieces displayed.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Methodically organized by category, color, and season for efficiency.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Loosely arranged by feeling with creative storage solutions.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Strategically organized for maximum versatility and outfit planning.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Arranged by mood and emotional connection rather than practicality.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Colorful and visual with frequent rearranging to keep things fresh.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Showcasing statement pieces with plenty of room for each item to shine.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "A creative mix that might look chaotic but makes sense to me.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal and precise with only essential pieces perfectly arranged.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Unconventional organization that challenges traditional closet systems.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your approach to fashion rules is...",
    options: [
      {
        text: "I appreciate classic guidelines that have stood the test of time.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "I understand the rules and thoughtfully decide when to follow them.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Rules are helpful starting points, but I follow my creative instincts.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "I study the rules to understand why they exist before deciding to use them.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "I care more about emotional resonance than following conventions.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Rules are made to be played with - fashion should be fun!",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "I make my own rules and set trends rather than following them.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "What rules? I wear what feels authentic in the moment.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I master the rules before mindfully breaking them with intention.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I deliberately challenge and subvert fashion rules as a form of expression.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "When you're feeling uninspired with your style, you...",
    options: [
      {
        text: "Look to classic films, vintage photographs, or timeless style icons.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Return to trusted formulas and quality basics while seeking thoughtful inspiration.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Connect with nature or art to spark creativity and fresh perspectives.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Analyze what's not working and research strategic solutions.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Explore emotions and moods to find a feeling I want to express.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Try something completely different just for fun and see what happens!",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Go shopping for a bold new statement piece to reignite my passion.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "Take a break from thinking about it and trust inspiration will return naturally.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Strip everything back to basics and rebuild with only what truly resonates.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Look to unexpected sources outside of fashion for boundary-pushing ideas.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "Your jewelry collection could be described as...",
    options: [
      {
        text: "Vintage-inspired pieces with sentimental value and romantic details.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "Thoughtfully curated quality pieces that work well together.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "Organic shapes and natural materials with artistic touches.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "Versatile pieces strategically chosen for maximum styling potential.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "Dreamy, ethereal pieces that evoke emotion and tell stories.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "Playful, colorful items that bring joy and start conversations.",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "Bold statement pieces that command attention and express confidence.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "An eclectic mix collected from travels and meaningful moments.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "Minimal but impactful pieces with clean lines and perfect proportions.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "Avant-garde designs that challenge traditional notions of jewelry.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
  {
    question: "When you see a fashion trend you dislike, your reaction is...",
    options: [
      {
        text: "I prefer timeless styles that don't go in and out of fashion.",
        archetype: "The Timeless Romantic",
        score: 1,
        emoji: "🪽",
      },
      {
        text: "I consider why it doesn't work for me and focus on what does.",
        archetype: "The Grounded Stylist",
        score: 2,
        emoji: "🪞",
      },
      {
        text: "I appreciate that different styles work for different people's self-expression.",
        archetype: "The Natural Creative",
        score: 3,
        emoji: "🌿",
      },
      {
        text: "I analyze why the trend exists and what need it's fulfilling.",
        archetype: "The Intentional Dresser",
        score: 4,
        emoji: "📐",
      },
      {
        text: "I focus on styles that emotionally resonate with me instead.",
        archetype: "The Sentimental Dreamer",
        score: 5,
        emoji: "🌙",
      },
      {
        text: "I might try it anyway just for fun - sometimes I'm surprised!",
        archetype: "The Playful Explorer",
        score: 6,
        emoji: "🎨",
      },
      {
        text: "I confidently stick to my bold personal style regardless of trends.",
        archetype: "The Confident Maximalist",
        score: 7,
        emoji: "💋",
      },
      {
        text: "I don't worry about liking or disliking trends - I just do what feels right.",
        archetype: "The Free Spirit",
        score: 8,
        emoji: "🔥",
      },
      {
        text: "I appreciate that eliminating what doesn't work helps refine my aesthetic.",
        archetype: "The Magnetic Minimalist",
        score: 9,
        emoji: "🖤",
      },
      {
        text: "I'm interested in why I dislike it and what that reveals about my values.",
        archetype: "The Visionary Dresser",
        score: 10,
        emoji: "🧬",
      },
    ],
  },
]
