export const whisperQuotes = [
  // Classic Literature & Poetry (1-50)
  "I am not afraid of storms, for I'm learning how to sail my ship. — Louisa May Alcott",
  "What is it you plan to do with your one wild and precious life? — Mary Oliver",
  "I must have flowers, always, and always. — Claude Monet",
  "The earth laughs in flowers. — Ralph Waldo Emerson",
  "She walks in beauty, like the night of cloudless climes and starry skies. — Lord Byron",
  "We loved with a love that was more than love. — Edgar Allan Poe",
  "My heart is, and always will be, yours. — Jane Austen",
  "Whatever our souls are made of, his and mine are the same. — Emily Brontë",
  "If I had a flower for every time I thought of you… I could walk through my garden forever. — Alfred Lord Tennyson",
  "Even the darkest night will end and the sun will rise. — Victor Hugo",
  "I took a deep breath and listened to the old brag of my heart. I am, I am, I am. — Sylvia Plath",
  "Let me live, love, and say it well in good sentences. — Sylvia Plath",
  "And you? When will you begin that long journey into yourself? — Rumi",
  "We are all broken. That's how the light gets in. — Ernest Hemingway",
  "There are years that ask questions and years that answer. — Zora Neale Hurston",
  "I am deliberate and afraid of nothing. — Audre Lorde",
  "The most courageous act is still to think for yourself. Aloud. — Coco Chanel",
  "There is no gate, no lock, no bolt that you can set upon the freedom of my mind. — Virginia Woolf",
  "A woman is like a tea bag – you can't tell how strong she is until you put her in hot water. — Eleanor Roosevelt",
  "There is no exquisite beauty… without some strangeness in the proportion. — Edgar Allan Poe",

  // Romantic & Dreamy (21-40)
  "She wasn't doing a thing that I could see, except standing there leaning on the balcony railing, holding the universe together. — J.D. Salinger",
  "Magic is believing in yourself. If you can do that, you can make anything happen. — Johann Wolfgang von Goethe",
  "We are all stardust and stories. — Erin Morgenstern",
  "And above all, watch with glittering eyes the whole world around you... — Roald Dahl",
  "You belong somewhere you feel free. — Tom Petty",
  "Somewhere, something incredible is waiting to be known. — Carl Sagan",
  "I want to be improbable and beautiful and afraid of nothing. — Waylon H. Lewis",
  "The soul always knows what to do to heal itself. The challenge is to silence the mind. — Caroline Myss",
  "Be soft. Do not let the world make you hard. — Iain Thomas",
  "I am made of love and light, even on my darkest days. — Nikita Gill",
  "Feelings are just visitors. Let them come and go. — Mooji",
  "There is a kind of beauty in imperfection. — Conrad Hall",
  "Your emotions are the colors of your soul. — Maya Angelou",
  "Her soul was too deep to explore by those who always swam in the shallow end. — A.J. Lawless",
  "She wore her scars as her best attire. A stunning dress made of hellfire. — Daniel Saint",
  "You do not just wake up and become the butterfly — growth is a process. — Rupi Kaur",
  "And the day came when the risk to remain tight in a bud was more painful than the risk it took to blossom. — Anaïs Nin",
  "Stay wild, moon child.",
  "She was a wildflower in love with the moon.",
  "You are a wildflower in a field of roses.",

  // Empowerment & Self-Love (41-60)
  "You are not too much. You're a blooming universe.",
  "Your softness is your strength.",
  "This bracelet chose you.",
  "You're not behind. You're blooming on your own clock.",
  "Everything you feel is valid and holy.",
  "She had a galaxy in her eyes, a universe in her soul.",
  "She dreamed in soft lavender and bloomed in wild grace.",
  "You are magic ✨",
  "Breathe in peace, breathe out love.",
  "Your story is still being written.",
  "Trust the timing of your life.",
  "You are exactly where you need to be.",
  "Your heart knows the way.",
  "Dance to the rhythm of your own soul.",
  "You are a poem written in stardust.",
  "Let your light shine, even in the darkness.",
  "You are worthy of all the love in the world.",
  "Your dreams are valid and beautiful.",
  "You are stronger than you know.",
  "Embrace your beautiful chaos.",

  // Literary Classics (61-80)
  "It is never too late to be what you might have been. — George Eliot",
  "The very first moment I beheld him, my heart was irrevocably gone. — Jane Austen",
  "I have waited for this opportunity for more than half a century, to repeat to you once again my vow of eternal fidelity and everlasting love. — Gabriel García Márquez",
  "You pierce my soul. I am half agony, half hope. — Jane Austen",
  "I would rather spend one lifetime with you, than face all the ages of this world alone. — J.R.R. Tolkien",
  "In vain I have struggled. It will not do. My feelings will not be repressed. — Jane Austen",
  "I love you without knowing how, or when, or from where. — Pablo Neruda",
  "You are my heart, my life, my one and only thought. — Arthur Conan Doyle",
  "I carry your heart with me (I carry it in my heart). — E.E. Cummings",
  "She was beautiful, but not like those girls in the magazines. She was beautiful, for the way she thought. — F. Scott Fitzgerald",
  "I fell in love the way you fall asleep: slowly, and then all at once. — John Green",
  "You have bewitched me, body and soul. — Jane Austen",
  "I would not wish any companion in the world but you. — William Shakespeare",
  "Doubt thou the stars are fire; doubt that the sun doth move; doubt truth to be a liar; but never doubt I love. — William Shakespeare",
  "When you realize you want to spend the rest of your life with somebody, you want the rest of your life to start as soon as possible. — Nora Ephron",
  "I have crossed oceans of time to find you. — Bram Stoker",
  "You should be kissed and often, and by someone who knows how. — Margaret Mitchell",
  "I love her and that's the beginning and end of everything. — F. Scott Fitzgerald",
  "She was life itself. Wild and free. Wonderfully chaotic. A perfectly put together mess. — Unknown",
  "I am catastrophically in love with you. — Cassandra Clare",

  // Poetry & Verse (81-100)
  "Tell me, what else should I have done? Doesn't everything die at last, and too soon? — Mary Oliver",
  "Instructions for living a life: Pay attention. Be astonished. Tell about it. — Mary Oliver",
  "Someone I loved once gave me a box full of darkness. It took me years to understand that this too, was a gift. — Mary Oliver",
  "Wild geese, you do not have to be good. — Mary Oliver",
  "The world offers itself to your imagination. — Mary Oliver",
  "I want to think again of dangerous and noble things. — Mary Oliver",
  "Tell me about despair, yours, and I will tell you mine. — Mary Oliver",
  "Poetry, to be alive at all, must be born out of blood, sweat and tears. — Langston Hughes",
  "I dwell in possibility. — Emily Dickinson",
  "Hope is the thing with feathers that perches in the soul. — Emily Dickinson",
  "I'm nobody! Who are you? Are you nobody, too? — Emily Dickinson",
  "If I can stop one heart from breaking, I shall not live in vain. — Emily Dickinson",
  "Forever is composed of nows. — Emily Dickinson",
  "The brain is wider than the sky. — Emily Dickinson",
  "I celebrate myself, and sing myself. — Walt Whitman",
  "Keep your face always toward the sunshine—and shadows will fall behind you. — Walt Whitman",
  "We were together. I forget the rest. — Walt Whitman",
  "Resist much, obey little. — Walt Whitman",
  "Do I contradict myself? Very well then I contradict myself, I am large, I contain multitudes. — Walt Whitman",
  "The powerful play goes on, and you may contribute a verse. — Walt Whitman",

  // Modern Literature (101-120)
  "The only way out is through. — Robert Frost",
  "Two roads diverged in a wood, and I— I took the one less traveled by, and that has made all the difference. — Robert Frost",
  "In three words I can sum up everything I've learned about life: it goes on. — Robert Frost",
  "The woods are lovely, dark and deep. But I have promises to keep. — Robert Frost",
  "Poetry is when an emotion has found its thought and the thought has found words. — Robert Frost",
  "We are what we choose to become. — Chuck Palahniuk",
  "The cave you fear to enter holds the treasure you seek. — Joseph Campbell",
  "Your task is not to seek for love, but merely to seek and find all the barriers within yourself that you have built against it. — Rumi",
  "Let yourself be silently drawn by the strange pull of what you really love. It will not lead you astray. — Rumi",
  "The wound is the place where the Light enters you. — Rumi",
  "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself. — Rumi",
  "Sell your cleverness and buy bewilderment. — Rumi",
  "Don't grieve. Anything you lose comes round in another form. — Rumi",
  "The breeze at dawn has secrets to tell you. Don't go back to sleep! — Rumi",
  "What you seek is seeking you. — Rumi",
  "Be like melting snow — wash yourself of yourself. — Rumi",
  "In your light I learn how to love. In your beauty, how to make poems. — Rumi",
  "Let the beauty we love be what we do. — Rumi",
  "Raise your words, not voice. It is rain that grows flowers, not thunder. — Rumi",
  "The art of knowing is knowing what to ignore. — Rumi",

  // Feminine Power (121-140)
  "A girl should be two things: who and what she wants. — Coco Chanel",
  "The most alluring thing a woman can have is confidence. — Beyoncé",
  "I am not free while any woman is unfree, even when her shackles are very different from my own. — Audre Lorde",
  "If you want something said, ask a man; if you want something done, ask a woman. — Margaret Thatcher",
  "Well-behaved women seldom make history. — Laurel Thatcher Ulrich",
  "A woman with a voice is, by definition, a strong woman. — Melinda Gates",
  "The question isn't who's going to let me; it's who's going to stop me. — Ayn Rand",
  "I raise up my voice—not so I can shout, but so that those without a voice can be heard. — Malala Yousafzai",
  "You are more powerful than you know; you are beautiful just as you are. — Melissa Etheridge",
  "A strong woman looks a challenge dead in the eye and gives it a wink. — Gina Carey",
  "She believed she could, so she did. — R.S. Grey",
  "Be yourself; everyone else is already taken. — Oscar Wilde",
  "You yourself, as much as anybody in the entire universe, deserve your love and affection. — Buddha",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "Don't let yesterday take up too much of today. — Will Rogers",
  "You learn more from failure than from success. Don't let it stop you. Failure builds character. — Unknown",
  "If you are working on something that you really care about, you don't have to be pushed. The vision pulls you. — Steve Jobs",
  "People who are crazy enough to think they can change the world, are the ones who do. — Rob Siltanen",
  "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten. — Neil Gaiman",
  "Yesterday is history, tomorrow is a mystery, today is a gift of God, which is why we call it the present. — Bill Keane",

  // Nature & Beauty (141-160)
  "In every walk with nature, one receives far more than he seeks. — John Muir",
  "Look deep into nature, and then you will understand everything better. — Albert Einstein",
  "Nature does not hurry, yet everything is accomplished. — Lao Tzu",
  "The clearest way into the Universe is through a forest wilderness. — John Muir",
  "Heaven is under our feet as well as over our heads. — Henry David Thoreau",
  "I went to the woods to live deliberately. — Henry David Thoreau",
  "All good things are wild and free. — Henry David Thoreau",
  "An early-morning walk is a blessing for the whole day. — Henry David Thoreau",
  "I love to think of nature as an unlimited broadcasting station, through which God speaks to us every hour, if we will only tune in. — George Washington Carver",
  "The poetry of the earth is never dead. — John Keats",
  "A thing of beauty is a joy forever. — John Keats",
  "Beauty is truth, truth beauty. — John Keats",
  "I almost wish we were butterflies and liv'd but three summer days. — John Keats",
  "The butterfly counts not months but moments, and has time enough. — Rabindranath Tagore",
  "Just living is not enough... one must have sunshine, freedom, and a little flower. — Hans Christian Andersen",
  "Where flowers bloom, so does hope. — Lady Bird Johnson",
  "Every flower is a soul blossoming in nature. — Gerard De Nerval",
  "A flower does not think of competing with the flower next to it. It just blooms. — Zen Shin",
  "Like wildflowers; you must allow yourself to grow in all the places people thought you never would. — E.V.",
  "She is a flower, but she isn't soft; when her petals fall, they hit like bullets. — Unknown",

  // Dreams & Aspirations (161-180)
  "All our dreams can come true, if we have the courage to pursue them. — Walt Disney",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "A dream is a wish your heart makes. — Cinderella",
  "Dreams don't work unless you do. — John C. Maxwell",
  "The biggest adventure you can take is to live the life of your dreams. — Oprah Winfrey",
  "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. — Roy T. Bennett",
  "Dreams are the touchstones of our characters. — Henry David Thoreau",
  "All that we see or seem is but a dream within a dream. — Edgar Allan Poe",
  "I have spread my dreams under your feet; Tread softly because you tread on my dreams. — W.B. Yeats",
  "Hold fast to dreams, for if dreams die, life is a broken-winged bird that cannot fly. — Langston Hughes",
  "A dream you dream alone is only a dream. A dream you dream together is reality. — Yoko Ono",
  "Dreams are illustrations from the book your soul is writing about you. — Marsha Norman",
  "The dream was always running ahead of me. To catch up, to live for a moment in unison with it, that was the miracle. — Anaïs Nin",
  "Dreams are the seeds of change. Nothing ever grows without a seed, and nothing ever changes without a dream. — Debby Boone",
  "Dreams are renewable. No matter what our age or condition, there are still untapped possibilities within us and new beauty waiting to be born. — Dale Turner",
  "Dreams pass into the reality of action. From the actions stems the dream again; and this interdependence produces the highest form of living. — Anaïs Nin",
  "Dreams are today's answers to tomorrow's questions. — Edgar Cayce",
  "Dreams are the royal road to the unconscious. — Sigmund Freud",
  "Dreams are whispers from the soul. — Unknown",
  "Follow your dreams, they know the way. — Kobi Yamada",

  // Love & Relationships (181-200)
  "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage. — Lao Tzu",
  "The best love is the kind that awakens the soul and makes us reach for more. — Nicholas Sparks",
  "Love is composed of a single soul inhabiting two bodies. — Aristotle",
  "Where there is love there is life. — Mahatma Gandhi",
  "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope. — Maya Angelou",
  "The greatest happiness of life is the conviction that we are loved; loved for ourselves, or rather, loved in spite of ourselves. — Victor Hugo",
  "Love is not about how many days, months, or years you have been together. Love is about how much you love each other every single day. — Unknown",
  "Love is when the other person's happiness is more important than your own. — H. Jackson Brown Jr.",
  "The best thing to hold onto in life is each other. — Audrey Hepburn",
  "Love is a friendship set to music. — Joseph Campbell",
  "Love is the bridge between you and everything. — Rumi",
  "Love is the flower you've got to let grow. — John Lennon",
  "Love is not finding someone to live with; it's finding someone you can't live without. — Rafael Ortiz",
  "Love is the master key that opens the gates of happiness. — Oliver Wendell Holmes",
  "Love is a canvas furnished by nature and embroidered by imagination. — Voltaire",
  "Love is the poetry of the senses. — Honoré de Balzac",
  "Love is the wisdom of the fool and the folly of the wise. — Samuel Johnson",
  "Love is a game that two can play and both win. — Eva Gabor",
  "Love is the only force capable of transforming an enemy into a friend. — Martin Luther King Jr.",
  "Love yourself first and everything else falls into line. — Lucille Ball",
]

export function getRandomWhisper(): string {
  const validQuotes = whisperQuotes.filter((quote) => quote && quote.trim().length > 0)

  if (validQuotes.length === 0) {
    return "You are magic ✨" // Fallback
  }

  const randomQuote = validQuotes[Math.floor(Math.random() * validQuotes.length)]
  return randomQuote.trim()
}

// Add a function to get a specific quote safely
export function getWhisperByIndex(index: number): string {
  if (index < 0 || index >= whisperQuotes.length) {
    return getRandomWhisper()
  }

  const quote = whisperQuotes[index]
  return quote && quote.trim() ? quote.trim() : getRandomWhisper()
}
